# no version needed since 2020
services:
  jekyll:
    image: bretfisher/jekyll-serve
    container_name: mmc-staff
    working_dir: /srv-jekyll
    volumes:
      - .:/srv-jekyll
    ports:
      - '5744:5744'
      - '35744:35744'
    command: |
      bundle exec jekyll serve
      --trace --force_polling
      --host 0.0.0.0
      --port 5744
      --livereload
      --livereload-port 35744
